### ISSUE TITLE
Implement abstraction layer for the USB OTG module

### ISSUE THREAD

**Issue by lucas-yotsui** [lucas-yotsui/ZigOnSTM32#11]
## Tasks
For this issue to be considered completed, the following tasks must be fulfilled: 

### Implementation
- [ ] Map all the registers related to the USB OTG module.
- [ ] Implement functions for abstracting register access. 
- [ ] Implement the USB protocol itself. Maybe not all of it, but the basics like the most common descriptors and all that.
_**NOTE:** Take some time to implement the USB protocol properly. It is extremely complex and will require some extra attention_.

### Documentation
- [ ] Document the role of each register.
- [ ] Document the role of each bit on each register.
- [ ] Document how to use all the functions.

### Testing
- [ ] Write unit tests for all that can be tested in such a way
- [ ] Test the rest of the functionality manually and ensure everything works properly.
