### ISSUE TITLE
Implement abstraction layer for the SPI modules

### ISSUE THREAD

**Issue by lucas-yotsui** [lucas-yotsui/ZigOnSTM32#9]
## Tasks
For this issue to be considered completed, the following tasks must be fulfilled: 

### Implementation
- [ ] Map all the registers related to the SPI modules.
- [ ] Implement functions for abstracting register access. 
_**NOTE:** Investigate how to use the DMA module for sending or receiving data through this interface and if it is worth the effort_.

### Documentation
- [ ] Document the role of each register.
- [ ] Document the role of each bit on each register.
- [ ] Document how to use all the functions.

### Testing
- [ ] Write unit tests for all that can be tested in such a way
- [ ] Test the rest of the functionality manually and ensure everything works properly.
